services:
        web:
                image: keymetrics/pm2:14-alpine
                working_dir: /server
                volumes:
                        - ./server:/server
                        - ./static:/server/static
                ports:
                        - "3000:3000"
                command: npm start
        mysql:
                image: mysql:8
                platform: linux/arm64 # 本地 mac m1
                volumes:
                        - ./data:/var/lib/mysql
                environment:
                        - MYSQL_ROOT_PASSWORD=123456
                        - MYSQL_DATABASE=koa_docker
                ports:
                        - "3306:3306"
        nginx:
                image: nginx:1.17
                volumes:
                        - ./static:/server/static
                        - ./conf/default.conf:/etc/nginx/conf.d/default.conf
                ports:
                        - "80:80"
